#define CATCH_CONFIG_MAIN
#include "catch.hpp"
#include "schedule.h"
#include "assignments.h"
#include <sstream>
using std::ostringstream;

/*****************************************************************************
 * do not edit this file
 ****************************************************************************/




